name: betfund
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  icons_plus: ^5.0.0
  toastification: ^2.0.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  dotted_dashed_line: ^0.0.3
  date_format: ^2.0.7
  custom_pop_up_menu: ^1.2.4
  ripple_wave: ^0.1.4
  fl_chart: ^0.68.0
  syncfusion_flutter_sliders: ^26.1.35
  linear_progress_bar: ^1.1.1
  vertical_tab_bar_view: ^0.0.1
  flutter_simple_candlesticks: ^1.0.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
